// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yueuzwikkfwvqstfzjbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZXV6d2lra2Z3dnFzdGZ6amJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzA3ODAsImV4cCI6MjA2MTU0Njc4MH0.7vC8YAj79-x4bs0K6P8kljDcu8fGIMlFpCPHBFQZwRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);